from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable


@dataclass(frozen=True)
class EdgeSignature:
    """Stable geometric intent for a planned edge treatment.

    This is deliberately a design-time signature, not a SolidWorks topology ID.
    Chamfer/fillet operations can split topology and create new small edges, so
    the runtime should only treat explicitly planned original edges.
    """

    axis: str
    radius_mm: float
    z_mm: float
    kind: str
    mode: str = "radial"
    tolerance_mm: float = 0.01

    def key(self) -> str:
        radius_bucket = round(self.radius_mm / self.tolerance_mm)
        z_bucket = round(self.z_mm / self.tolerance_mm)
        return (
            f"axis={self.axis}|r_bucket={radius_bucket}|z_bucket={z_bucket}|"
            f"kind={self.kind}|mode={self.mode}"
        )

    def label(self) -> str:
        return (
            f"{self.axis} {self.kind} r={self.radius_mm:g}mm "
            f"z={self.z_mm:g}mm mode={self.mode}"
        )


@dataclass(frozen=True)
class EdgeTreatmentRecord:
    signature: EdgeSignature
    operation: str
    feature_name: str


class EdgeTreatmentRegistry:
    """Prevent repeated chamfer/fillet treatment of the same planned edge."""

    def __init__(self, allowed_signatures: Iterable[EdgeSignature] | None = None):
        self._allowed = {}
        self._treated: dict[str, EdgeTreatmentRecord] = {}
        self._generated_blacklist: set[str] = set()
        for signature in allowed_signatures or []:
            self.allow(signature)

    def allow(self, signature: EdgeSignature) -> None:
        self._allowed[signature.key()] = signature

    def is_allowed(self, signature: EdgeSignature) -> bool:
        return signature.key() in self._allowed

    def treated_record(self, signature: EdgeSignature) -> EdgeTreatmentRecord | None:
        return self._treated.get(signature.key())

    def can_treat(self, signature: EdgeSignature) -> tuple[bool, str]:
        key = signature.key()
        if self._allowed and key not in self._allowed:
            return False, f"edge is not in planned original-edge list: {signature.label()}"
        if key in self._generated_blacklist:
            return False, f"edge is blacklisted as generated by an earlier treatment: {signature.label()}"
        record = self._treated.get(key)
        if record:
            return (
                False,
                f"edge already {record.operation} treated by {record.feature_name}: "
                f"{signature.label()}",
            )
        return True, "ok"

    def filter_untreated(
        self,
        signatures: Iterable[EdgeSignature],
        *,
        operation: str,
        feature_name: str,
        required: bool,
        log=print,
    ) -> list[EdgeSignature]:
        accepted: list[EdgeSignature] = []
        seen_in_feature: set[str] = set()
        for signature in signatures:
            key = signature.key()
            if key in seen_in_feature:
                log(f"[EDGE] skip duplicate edge inside {feature_name}: {signature.label()}")
                continue
            seen_in_feature.add(key)

            ok, reason = self.can_treat(signature)
            if not ok:
                message = f"[EDGE] skip {operation} for {feature_name}: {reason}"
                if required:
                    raise RuntimeError(message)
                log(message)
                continue
            accepted.append(signature)
        return accepted

    def mark_treated(self, signatures: Iterable[EdgeSignature], *, operation: str, feature_name: str) -> None:
        for signature in signatures:
            self._treated[signature.key()] = EdgeTreatmentRecord(signature, operation, feature_name)

    def blacklist_generated_edges(self, feature_name: str) -> None:
        """Placeholder hook for future topology-aware generated-edge detection.

        Today the effective protection is stricter: only planned original-edge
        signatures are selectable for treatment.
        """
        self._generated_blacklist.add(f"generated_by={feature_name}")

    def records(self) -> list[dict[str, str]]:
        return [
            {
                "signature": record.signature.label(),
                "operation": record.operation,
                "feature_name": record.feature_name,
            }
            for record in self._treated.values()
        ]


def circular_edge_signature(
    radius_mm: float,
    z_mm: float,
    *,
    outer: bool,
    mode: str = "radial",
    axis: str = "AXIS_CENTER_BORE",
) -> EdgeSignature:
    kind = "outer_circular_edge" if outer else "inner_circular_edge"
    return EdgeSignature(axis=axis, radius_mm=radius_mm, z_mm=z_mm, kind=kind, mode=mode)

